### ISSUE TITLE
Blend Map export

### ISSUE THREAD

**Issue by Gusher** [Snowapril/Procedural-Terrain-Estimator#27] opened 2021-03-13 20:14 UTC
Am not sure if its bug or am missing something but why is exported blend map transparent with black spots and not like depicted in export dialog RGBA blendmap?

**Comment by Snowapril** [comment] 2021-03-14 06:05
It is because we use all R,G,B,A channels for texture splatting in renderer. 
Dialog RGBA blendmap show you image without alpha channel for visually good looking.
The transparent with black spots what you are looking in the filesystem is caused by alpha channel of the blendmap. 
It is normal behavior :)

**Comment by Gusher** [comment] 2021-03-14 11:16
Oh I see, so how do I go about making it look like without alpha channel?

**Comment by Snowapril** [comment] 2021-03-14 11:31
Well,, there is shortcut for removing alpha channel, such as opening it with paint tool and saving it again.
But why do you want to see blendmap with only RGB channels?
Removing alpha channel from blend map means removing one terrain layer from the result.

**Comment by Gusher** [comment] 2021-03-14 14:06
Good point, I need to keep all 4....

**Comment by Snowapril** [comment] 2021-03-14 16:05
Thank you for your interest to my repo.
Seems like working well.
I'll close the issue. Please re-open the issue whenever you need help 😁

**Closed as completed by Snowapril** 2021-03-14 16:05 UTC
